# Generated by Django 3.2 on 2021-04-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Descriptive name of translation",
                        max_length=255,
                        verbose_name="Translation's name",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Key used for translation recognition",
                        max_length=255,
                        verbose_name="Key",
                    ),
                ),
                (
                    "value_pl",
                    models.CharField(
                        help_text="Value for translation",
                        max_length=255,
                        verbose_name="Value",
                    ),
                ),
                (
                    "value_en",
                    models.CharField(
                        help_text="Value for translation",
                        max_length=255,
                        verbose_name="Value",
                    ),
                ),
            ],
        ),
    ]
