---
# handlers file for locale

- name: localectl set-locale
  ansible.builtin.command: localectl set-locale LANG={{ locale_lang }}
  when:
    - ansible_connection != "docker"
    - ansible_distribution != "Ubuntu"
    - ansible_distribution  != "Debian"
