---
- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ cert_item.domains | first | replace('*.', '') }}/fullchain.pem
  register: letsencrypt_cert
  tags:
    - certbot
    - certbot_create_certs

- name: Ensure that webroot for certbot exists
  file:
    path: "{{ certbot_webroot_path }}"
    recurse: yes
    state: directory
  tags:
    - certbot
    - certbot_create_certs

- name: Generate new certificate if one doesn't exist.
  command:
    cmd: "{{ certbot_create_command }}"
  register: certbot_command_result
  changed_when: not 'no action taken' in certbot_command_result.stdout
  when: not letsencrypt_cert.stat.exists
  notify: "Reload web server"
  tags:
    - certbot
    - certbot_create_certs
