---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false
  tags:
    - nginx

- name: Ensure nginx is installed.
  apt:
    name: "{{ nginx_package_name }}"
    state: present
    default_release: "{{ nginx_default_release }}"
  tags:
    - nginx
